/* The following code was generated by JFlex 1.4.3 on 17/03/22 18:37 */

package com.example.proyecto.Model;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/03/22 18:37 from the specification file
 * <tt>D:/UP/Cuatri 8/Compiladores e interpretes/Corte 1/ProyectoC1/src/main/java/com/example/proyecto/Model/LexerCup.flex</tt>
 */
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  2,  0,  0,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     2,  0,  0,  0,  0,  0,  0,  0, 26, 27,  0,  0, 28,  0,  0,  0, 
    33, 30, 30, 31, 31, 31, 32, 32, 32, 32,  0, 29,  0,  0,  0,  0, 
     0, 10, 14,  8,  6,  7, 15, 22, 19,  3,  1, 25, 11,  9,  4, 12, 
    23,  1, 16, 17,  5, 13, 20,  1, 21, 18,  1,  0,  0,  0,  0, 24, 
     0, 10, 14,  8,  6,  7, 15, 22, 19,  3,  1, 25, 11,  9,  4, 12, 
    23,  1, 16, 17,  5, 13, 20,  1, 21, 18,  1,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\20\2\1\4\1\5\1\6"+
    "\1\7\2\10\1\0\30\2\2\10\1\11\1\2\1\12"+
    "\16\2\1\13\6\2\1\14\1\2\1\15\2\2\1\16"+
    "\1\17\2\2\1\20\3\2\1\21\4\2\1\22\1\2"+
    "\1\23\2\2\1\24\4\2\1\25\6\2\1\0\1\2"+
    "\1\26\12\2\1\27\1\30\7\2\1\31\2\2\1\32"+
    "\7\2\1\33\1\34\1\35\1\36\1\2\1\37\1\40"+
    "\3\2\1\41\1\42\1\43\1\44\2\2\1\45\4\2"+
    "\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\u01dc\0\u01fe"+
    "\0\u0220\0\u0242\0\u0264\0\u0286\0\42\0\42\0\42\0\42"+
    "\0\u02a8\0\u02ca\0\u02ec\0\u030e\0\u0330\0\u0352\0\u0374\0\u0396"+
    "\0\u03b8\0\u03da\0\u03fc\0\u041e\0\u0440\0\u0462\0\u0484\0\u04a6"+
    "\0\u04c8\0\u04ea\0\u050c\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6"+
    "\0\u05d8\0\u05fa\0\u061c\0\u063e\0\42\0\104\0\u0660\0\104"+
    "\0\u0682\0\u06a4\0\u06c6\0\u06e8\0\u070a\0\u072c\0\u074e\0\u0770"+
    "\0\u0792\0\u07b4\0\u07d6\0\u07f8\0\u081a\0\u083c\0\104\0\u085e"+
    "\0\u0880\0\u08a2\0\u08c4\0\u08e6\0\u0908\0\104\0\u092a\0\104"+
    "\0\u094c\0\u096e\0\u0990\0\104\0\u09b2\0\u09d4\0\u09f6\0\u0a18"+
    "\0\u0a3a\0\u0a5c\0\104\0\u0a7e\0\u0aa0\0\u0ac2\0\u0ae4\0\104"+
    "\0\u0b06\0\104\0\u0b28\0\u0b4a\0\104\0\u0b6c\0\u0b8e\0\u0bb0"+
    "\0\u0bd2\0\104\0\u0bf4\0\u0c16\0\u0c38\0\u0c5a\0\u0c7c\0\u0c9e"+
    "\0\u0cc0\0\u0ce2\0\104\0\u0d04\0\u0d26\0\u0d48\0\u0d6a\0\u0d8c"+
    "\0\u0dae\0\u0dd0\0\u0df2\0\u0e14\0\u0e36\0\104\0\104\0\u0e58"+
    "\0\u0e7a\0\u0e9c\0\u0ebe\0\u0ee0\0\u0f02\0\u0f24\0\104\0\u0f46"+
    "\0\u0f68\0\104\0\u0f8a\0\u0fac\0\u0fce\0\u0ff0\0\u1012\0\u1034"+
    "\0\u1056\0\104\0\104\0\104\0\104\0\u1078\0\104\0\104"+
    "\0\u109a\0\u10bc\0\u10de\0\104\0\104\0\104\0\104\0\u1100"+
    "\0\u1122\0\104\0\u1144\0\u1166\0\u1188\0\u11aa\0\104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\3"+
    "\1\11\1\12\1\13\1\14\1\3\1\15\1\3\1\16"+
    "\1\17\1\20\1\21\1\3\1\22\2\3\1\23\1\2"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\2\32\1\2"+
    "\43\0\1\3\1\0\25\3\1\33\1\3\12\0\1\4"+
    "\40\0\1\3\1\0\1\3\1\34\23\3\1\33\1\3"+
    "\11\0\1\3\1\0\5\3\1\35\3\3\1\36\1\37"+
    "\6\3\1\40\3\3\1\33\1\3\11\0\1\3\1\0"+
    "\1\41\3\3\1\42\2\3\1\43\15\3\1\33\1\3"+
    "\11\0\1\3\1\0\4\3\1\44\2\3\1\45\1\3"+
    "\1\46\13\3\1\33\1\3\11\0\1\3\1\0\15\3"+
    "\1\47\2\3\1\50\4\3\1\33\1\3\11\0\1\3"+
    "\1\0\4\3\1\51\20\3\1\33\1\3\11\0\1\3"+
    "\1\0\12\3\1\52\12\3\1\33\1\3\11\0\1\3"+
    "\1\0\11\3\1\53\13\3\1\33\1\3\11\0\1\3"+
    "\1\0\16\3\1\54\6\3\1\33\1\3\11\0\1\3"+
    "\1\0\10\3\1\55\14\3\1\33\1\3\11\0\1\3"+
    "\1\0\4\3\1\56\20\3\1\33\1\3\11\0\1\3"+
    "\1\0\6\3\1\57\16\3\1\33\1\3\11\0\1\3"+
    "\1\0\4\3\1\60\20\3\1\33\1\3\11\0\1\3"+
    "\1\0\7\3\1\61\15\3\1\33\1\3\11\0\1\3"+
    "\1\0\15\3\1\62\7\3\1\33\1\3\11\0\1\3"+
    "\1\0\4\3\1\63\20\3\1\33\1\3\46\0\2\64"+
    "\1\65\1\64\36\0\4\65\1\0\1\3\1\0\25\3"+
    "\1\0\1\3\11\0\1\3\1\0\2\3\1\66\22\3"+
    "\1\33\1\3\11\0\1\3\1\0\20\3\1\67\4\3"+
    "\1\33\1\3\11\0\1\3\1\0\2\3\1\70\22\3"+
    "\1\33\1\3\11\0\1\3\1\0\10\3\1\71\14\3"+
    "\1\33\1\3\11\0\1\3\1\0\7\3\1\72\15\3"+
    "\1\33\1\3\11\0\1\3\1\0\1\3\1\73\4\3"+
    "\1\74\16\3\1\33\1\3\11\0\1\3\1\0\22\3"+
    "\1\75\2\3\1\33\1\3\11\0\1\3\1\0\13\3"+
    "\1\76\11\3\1\33\1\3\11\0\1\3\1\0\5\3"+
    "\1\77\17\3\1\33\1\3\11\0\1\3\1\0\2\3"+
    "\1\100\22\3\1\33\1\3\11\0\1\3\1\0\12\3"+
    "\1\101\12\3\1\33\1\3\11\0\1\3\1\0\4\3"+
    "\1\102\20\3\1\33\1\3\11\0\1\3\1\0\7\3"+
    "\1\103\15\3\1\33\1\3\11\0\1\3\1\0\3\3"+
    "\1\104\21\3\1\33\1\3\11\0\1\3\1\0\2\3"+
    "\1\105\22\3\1\33\1\3\11\0\1\3\1\0\1\3"+
    "\1\106\23\3\1\33\1\3\11\0\1\3\1\0\4\3"+
    "\1\107\20\3\1\33\1\3\11\0\1\3\1\0\11\3"+
    "\1\110\13\3\1\33\1\3\11\0\1\3\1\0\7\3"+
    "\1\111\15\3\1\33\1\3\11\0\1\3\1\0\7\3"+
    "\1\112\15\3\1\33\1\3\11\0\1\3\1\0\7\3"+
    "\1\113\15\3\1\33\1\3\11\0\1\3\1\0\15\3"+
    "\1\114\7\3\1\33\1\3\11\0\1\3\1\0\1\115"+
    "\24\3\1\33\1\3\11\0\1\3\1\0\17\3\1\116"+
    "\5\3\1\33\1\3\46\0\2\65\1\0\1\65\1\0"+
    "\1\3\1\0\7\3\1\117\15\3\1\33\1\3\11\0"+
    "\1\3\1\0\10\3\1\120\14\3\1\33\1\3\11\0"+
    "\1\3\1\0\15\3\1\121\7\3\1\33\1\3\11\0"+
    "\1\3\1\0\17\3\1\122\5\3\1\33\1\3\11\0"+
    "\1\3\1\0\4\3\1\123\20\3\1\33\1\3\11\0"+
    "\1\3\1\0\2\3\1\124\22\3\1\33\1\3\11\0"+
    "\1\3\1\0\10\3\1\125\14\3\1\33\1\3\11\0"+
    "\1\3\1\0\1\126\24\3\1\33\1\3\11\0\1\3"+
    "\1\0\4\3\1\127\2\3\1\130\15\3\1\33\1\3"+
    "\11\0\1\3\1\0\13\3\1\131\11\3\1\33\1\3"+
    "\11\0\1\3\1\0\7\3\1\132\15\3\1\33\1\3"+
    "\11\0\1\3\1\0\15\3\1\133\7\3\1\33\1\3"+
    "\11\0\1\3\1\0\1\134\24\3\1\33\1\3\11\0"+
    "\1\3\1\0\11\3\1\135\13\3\1\33\1\3\11\0"+
    "\1\3\1\0\23\3\1\136\1\3\1\33\1\3\11\0"+
    "\1\3\1\0\7\3\1\137\15\3\1\33\1\3\11\0"+
    "\1\3\1\0\10\3\1\140\14\3\1\33\1\3\11\0"+
    "\1\3\1\0\10\3\1\141\14\3\1\33\1\3\11\0"+
    "\1\3\1\0\15\3\1\142\7\3\1\33\1\3\11\0"+
    "\1\3\1\0\5\3\1\143\17\3\1\33\1\3\11\0"+
    "\1\3\1\0\6\3\1\144\16\3\1\33\1\3\11\0"+
    "\1\3\1\0\15\3\1\145\7\3\1\33\1\3\11\0"+
    "\1\3\1\0\5\3\1\146\17\3\1\33\1\3\11\0"+
    "\1\3\1\0\1\147\1\3\1\150\22\3\1\33\1\3"+
    "\11\0\1\3\1\0\16\3\1\151\6\3\1\33\1\3"+
    "\11\0\1\3\1\0\4\3\1\152\20\3\1\33\1\3"+
    "\11\0\1\3\1\0\6\3\1\153\16\3\1\33\1\3"+
    "\11\0\1\3\1\0\2\3\1\154\22\3\1\33\1\3"+
    "\11\0\1\3\1\0\13\3\1\155\11\3\1\33\1\3"+
    "\11\0\1\3\1\0\10\3\1\156\14\3\1\33\1\3"+
    "\11\0\1\3\1\0\2\3\1\157\22\3\1\33\1\3"+
    "\11\0\1\3\1\0\12\3\1\160\12\3\1\33\1\3"+
    "\11\0\1\3\1\0\25\3\1\161\1\3\11\0\1\3"+
    "\1\0\2\3\1\162\22\3\1\33\1\3\11\0\1\3"+
    "\1\0\2\3\1\163\22\3\1\33\1\3\11\0\1\3"+
    "\1\0\10\3\1\164\14\3\1\33\1\3\11\0\1\3"+
    "\1\0\20\3\1\165\4\3\1\33\1\3\11\0\1\3"+
    "\1\0\7\3\1\166\15\3\1\33\1\3\11\0\1\3"+
    "\1\0\20\3\1\167\4\3\1\33\1\3\11\0\1\3"+
    "\1\0\1\3\1\170\23\3\1\33\1\3\11\0\1\3"+
    "\1\0\4\3\1\171\20\3\1\33\1\3\11\0\1\3"+
    "\1\0\2\3\1\172\22\3\1\33\1\3\11\0\1\3"+
    "\1\0\7\3\1\173\15\3\1\33\1\3\11\0\1\3"+
    "\1\0\1\174\24\3\1\33\1\3\11\0\1\3\1\0"+
    "\7\3\1\175\15\3\1\33\1\3\11\0\1\3\1\0"+
    "\4\3\1\176\20\3\1\33\1\3\11\0\1\3\1\0"+
    "\4\3\1\177\20\3\1\33\1\3\11\0\1\3\1\0"+
    "\6\3\1\200\16\3\1\33\1\3\11\0\1\3\1\0"+
    "\1\201\24\3\1\0\1\3\11\0\1\3\1\0\4\3"+
    "\1\202\20\3\1\33\1\3\11\0\1\3\1\0\1\203"+
    "\24\3\1\33\1\3\11\0\1\3\1\0\7\3\1\204"+
    "\15\3\1\33\1\3\11\0\1\3\1\0\15\3\1\205"+
    "\7\3\1\33\1\3\11\0\1\3\1\0\7\3\1\206"+
    "\15\3\1\33\1\3\11\0\1\3\1\0\2\3\1\207"+
    "\22\3\1\33\1\3\11\0\1\3\1\0\22\3\1\210"+
    "\2\3\1\33\1\3\11\0\1\3\1\0\7\3\1\211"+
    "\15\3\1\33\1\3\11\0\1\3\1\0\10\3\1\212"+
    "\14\3\1\33\1\3\11\0\1\3\1\0\6\3\1\213"+
    "\16\3\1\33\1\3\11\0\1\3\1\0\16\3\1\214"+
    "\6\3\1\33\1\3\11\0\1\3\1\0\1\215\1\3"+
    "\1\216\22\3\1\33\1\3\11\0\1\3\1\0\1\3"+
    "\1\217\23\3\1\33\1\3\11\0\1\3\1\0\22\3"+
    "\1\220\2\3\1\33\1\3\11\0\1\3\1\0\1\3"+
    "\1\221\23\3\1\33\1\3\11\0\1\3\1\0\15\3"+
    "\1\222\7\3\1\33\1\3\11\0\1\3\1\0\17\3"+
    "\1\223\5\3\1\33\1\3\11\0\1\3\1\0\15\3"+
    "\1\224\7\3\1\33\1\3\11\0\1\3\1\0\2\3"+
    "\1\225\22\3\1\33\1\3\11\0\1\3\1\0\6\3"+
    "\1\226\16\3\1\33\1\3\11\0\1\3\1\0\4\3"+
    "\1\227\20\3\1\33\1\3\11\0\1\3\1\0\4\3"+
    "\1\230\20\3\1\33\1\3\11\0\1\3\1\0\1\3"+
    "\1\231\23\3\1\33\1\3\11\0\1\3\1\0\4\3"+
    "\1\232\20\3\1\33\1\3\11\0\1\3\1\0\5\3"+
    "\1\233\17\3\1\33\1\3\11\0\1\3\1\0\2\3"+
    "\1\234\22\3\1\33\1\3\11\0\1\3\1\0\2\3"+
    "\1\235\22\3\1\33\1\3\11\0\1\3\1\0\24\3"+
    "\1\236\1\33\1\3\11\0\1\3\1\0\2\3\1\237"+
    "\22\3\1\33\1\3\11\0\1\3\1\0\22\3\1\240"+
    "\2\3\1\33\1\3\11\0\1\3\1\0\15\3\1\241"+
    "\7\3\1\33\1\3\11\0\1\3\1\0\2\3\1\242"+
    "\22\3\1\33\1\3\11\0\1\3\1\0\4\3\1\243"+
    "\20\3\1\33\1\3\11\0\1\3\1\0\6\3\1\244"+
    "\16\3\1\33\1\3\11\0\1\3\1\0\4\3\1\245"+
    "\20\3\1\33\1\3\11\0\1\3\1\0\1\3\1\246"+
    "\23\3\1\33\1\3\11\0\1\3\1\0\2\3\1\247"+
    "\22\3\1\33\1\3\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4556];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\22\1\4\11\2\1\1\0\31\1\1\11"+
    "\73\1\1\0\66\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 38: 
          { return new Symbol(sym.autoi, yychar, yyline, yytext());
          }
        case 39: break;
        case 30: 
          { return new Symbol(sym.Tinytext, yychar, yyline, yytext());
          }
        case 40: break;
        case 9: 
          { return new Symbol(sym.Int, yychar, yyline, yytext());
          }
        case 41: break;
        case 31: 
          { return new Symbol(sym.Datetime, yychar, yyline, yytext());
          }
        case 42: break;
        case 20: 
          { return new Symbol(sym.Nchar, yychar, yyline, yytext());
          }
        case 43: break;
        case 34: 
          { return new Symbol(sym.Smallint, yychar, yyline, yytext());
          }
        case 44: break;
        case 14: 
          { return new Symbol(sym.Time, yychar, yyline, yytext());
          }
        case 45: break;
        case 33: 
          { return new Symbol(sym.Longtext, yychar, yyline, yytext());
          }
        case 46: break;
        case 2: 
          { return new Symbol(sym.identificador, yychar, yyline, yytext());
          }
        case 47: break;
        case 26: 
          { return new Symbol(sym.Decimal, yychar, yyline, yytext());
          }
        case 48: break;
        case 21: 
          { return new Symbol(sym.Table, yychar, yyline, yytext());
          }
        case 49: break;
        case 17: 
          { return new Symbol(sym.Char, yychar, yyline, yytext());
          }
        case 50: break;
        case 16: 
          { return new Symbol(sym.Date, yychar, yyline, yytext());
          }
        case 51: break;
        case 32: 
          { return new Symbol(sym.Database, yychar, yyline, yytext());
          }
        case 52: break;
        case 4: 
          { return new Symbol(sym.pa, yychar, yyline, yytext());
          }
        case 53: break;
        case 29: 
          { return new Symbol(sym.Nvarchar, yychar, yyline, yytext());
          }
        case 54: break;
        case 10: 
          { return new Symbol(sym.Not, yychar, yyline, yytext());
          }
        case 55: break;
        case 35: 
          { return new Symbol(sym.Timestamp, yychar, yyline, yytext());
          }
        case 56: break;
        case 11: 
          { return new Symbol(sym.Use, yychar, yyline, yytext());
          }
        case 57: break;
        case 24: 
          { return new Symbol(sym.Create, yychar, yyline, yytext());
          }
        case 58: break;
        case 37: 
          { return new Symbol(sym.Mediumtext, yychar, yyline, yytext());
          }
        case 59: break;
        case 13: 
          { return new Symbol(sym.Nulo, yychar, yyline, yytext());
          }
        case 60: break;
        case 18: 
          { return new Symbol(sym.Real, yychar, yyline, yytext());
          }
        case 61: break;
        case 15: 
          { return new Symbol(sym.Text, yychar, yyline, yytext());
          }
        case 62: break;
        case 6: 
          { return new Symbol(sym.coma, yychar, yyline, yytext());
          }
        case 63: break;
        case 5: 
          { return new Symbol(sym.pc, yychar, yyline, yytext());
          }
        case 64: break;
        case 23: 
          { return new Symbol(sym.Double, yychar, yyline, yytext());
          }
        case 65: break;
        case 12: 
          { return new Symbol(sym.key, yychar, yyline, yytext());
          }
        case 66: break;
        case 8: 
          { return new Symbol(sym.Longitud, yychar, yyline, yytext());
          }
        case 67: break;
        case 25: 
          { return new Symbol(sym.Tinyint, yychar, yyline, yytext());
          }
        case 68: break;
        case 28: 
          { return new Symbol(sym.primary, yychar, yyline, yytext());
          }
        case 69: break;
        case 27: 
          { return new Symbol(sym.Varchar, yychar, yyline, yytext());
          }
        case 70: break;
        case 36: 
          { return new Symbol(sym.Mediumint, yychar, yyline, yytext());
          }
        case 71: break;
        case 7: 
          { return new Symbol(sym.pcoma, yychar, yyline, yytext());
          }
        case 72: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 73: break;
        case 3: 
          { /*Ignore*/
          }
        case 74: break;
        case 19: 
          { return new Symbol(sym.Year, yychar, yyline, yytext());
          }
        case 75: break;
        case 22: 
          { return new Symbol(sym.Float, yychar, yyline, yytext());
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
