
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 03 20:35:51 CST 2022
//----------------------------------------------------

package com.example.proyecto.Model;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nvarchar = 17;
  public static final int Tinytext = 15;
  public static final int Nulo = 27;
  public static final int Double = 4;
  public static final int Real = 7;
  public static final int Table = 25;
  public static final int coma = 33;
  public static final int Mediumtext = 14;
  public static final int identificador = 35;
  public static final int Longitud = 36;
  public static final int Database = 24;
  public static final int Smallint = 8;
  public static final int Longtext = 13;
  public static final int key = 30;
  public static final int Nchar = 16;
  public static final int Text = 12;
  public static final int primary = 29;
  public static final int pc = 32;
  public static final int Int = 2;
  public static final int pa = 31;
  public static final int Float = 5;
  public static final int EOF = 0;
  public static final int Not = 26;
  public static final int error = 1;
  public static final int pcoma = 34;
  public static final int Timestamp = 22;
  public static final int Mediumint = 6;
  public static final int Char = 10;
  public static final int Datetime = 19;
  public static final int ERROR = 37;
  public static final int Create = 23;
  public static final int Time = 21;
  public static final int Tinyint = 9;
  public static final int autoi = 28;
  public static final int Date = 18;
  public static final int Varchar = 11;
  public static final int Decimal = 3;
  public static final int Year = 20;
}

